# docker-compose.yml

services:
  postgres:
    image: postgres:15
    container_name: ecommerce_pg
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: ecommerce_redis
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecommerce_web
    command: supervisord -c /etc/supervisor/conf.d/supervisord.conf
    volumes:
      - .:/app
    ports:
      - "8000:8000"  # FastAPI
    depends_on:
      - postgres
      - redis

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecommerce_worker
    command: celery -A app.celery_worker.celery worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - web
      - redis
      - postgres

  flower:
    image: mher/flower:2.0.1  # Specify a stable version
    container_name: ecommerce_flower
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - FLOWER_PORT=5555
    ports:
      - "5555:5555"
    depends_on:
      - redis

volumes:
  pg_data:
  redis_data:
