version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"      # AMQP protocol
      - "15672:15672"    # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: adminpassword

  mongodb:
    image: mongo:4.4
    container_name: mongodb
    ports:
      - "27017:27017"    # MongoDB port
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: mongopassword

  crawler:
    build: .
    depends_on:
      - rabbitmq
      - mongodb
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: adminpassword
      QUEUE_NAME: crawl_queue
      MONGO_URI: mongodb://mongouser:mongopassword@mongodb:27017/
      PROXY_LIST: ""  # Optional: e.g., "http://proxy1:port,http://proxy2:port"
    command: scrapy crawl product_spider

  webapp:
    build:
      context: .
      dockerfile: Dockerfile.webapp
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://mongouser:mongopassword@mongodb:27017/
    ports:
      - "8000:8000"
    command: python webapp.py

volumes:
  mongo-data:
